# Generated by Django 4.2.7 on 2023-11-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yousta', '0002_category_cloths_clothvarients_reviews_orders_offers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloths',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yousta.category'),
        ),
    ]
